name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          debug: true
          script: |
            whoami
            set -e

            cd /var/www/dinesh-seghal-backend/Dinesh-Sagel-Backend

            git fetch --all
            git reset --hard origin/main

            npm install

            pm2 restart dinesh-seghal-backend --update-env

            pm2 save